config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :steps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  has_many :steps
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  # GET /ingredients/1/edit
  def edit
    @recipe = Recipe.find(params[:recipe_id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to recipe_path(id: @ingredient.recipe_id)}
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to recipe_path(id: @ingredient.recipe_id), notice: 'Ingredient was successfully updated.'}
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @id = @ingredient.recipe_id
    @ingredient.destroy
    redirect_to recipe_url id: @id

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :quantity, :measure, :recipe_id)

    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end


  def new
    @recipe = Recipe.new
  end

  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_path(id: @recipe.id)}
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_path(id: @recipe.id), notice: 'Recipe saved.'}
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @recipe.destroy
    redirect_to recipes_url

  end

  def show
    @recipe = Recipe.find params[:id]
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :description)

    end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
  end

  # GET /steps/new
  def new
    @step = Step.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  # GET /steps/1/edit
  def edit
    @recipe = Recipe.find(params[:recipe_id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)

    respond_to do |format|
      if @step.save
        format.html { redirect_to recipe_path(id: @step.recipe_id)}
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to recipe_path(id: @step.recipe_id), notice: 'Step was successfully updated.'}
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @id = @step.recipe_id
    @step.destroy
    redirect_to recipe_url id: @id

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:description, :recipe_id)

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Edit ingredient</p>
    </div>
  </div>
</div>

<%= form_for @ingredient do |f| %>
<%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="name">Name:</label>
          <%= f.text_field :name, class: "form-control", id: "name" %>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-4">
          <label for="quantity">Quantity:</label>
          <%= f.number_field :quantity, class: "form-control", id: "quantity" %>
        </div>
        <div class="form-group col-lg-4">
          <label for="quantity">Unit of measurement:</label>
          <%= f.text_field :measure, class: "form-control", id: "measure" %>
        </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipe_path(id: params[:recipe_id]), class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/ingredients/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Add ingredient</p>
    </div>
  </div>
</div>

<%= form_for @ingredient do |f| %>
<%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="name">Name:</label>
          <%= f.text_field :name, class: "form-control", id: "name" %>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-4">
          <label for="quantity">Quantity:</label>
          <%= f.number_field :quantity, class: "form-control", id: "quantity" %>
        </div>
        <div class="form-group col-lg-4">
          <label for="quantity">Unit of measurement:</label>
          <%= f.text_field :measure, class: "form-control", id: "measure" %>
        </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipe_path(id: params[:recipe_id]), class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="description" content="This is a Rails study">
    <meta name="author" content="@flaviojmendes">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Edit this recipe.</p>
    </div>
  </div>
</div>

<%= form_for @recipe do |f| %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="name">Name:</label>
          <%= f.text_field :name, class: "form-control", id: "name" %>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="description">Description:</label>
          <%= f.text_area :description, class: "form-control", id: "description" %>
        </div>

    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipes_path, class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1>Recipes</h1>
    </div>
  </div>

  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p id="notice"><%= notice %><%= notice = '' %></p>
    </div>
  </div>
  <div class="row justify-content-md-center btn-row">
    <div class="col-lg-8">
      <%= link_to "+ Recipe", new_recipe_path, class: "btn btn-primary float-right" %>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-8">

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
          <tr>
            <td><%= link_to recipe.name, recipe %></td>
            <td><%= recipe.description %></td>
            <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %> |
                <%= link_to 'Edit', edit_recipe_path(recipe, id: recipe.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1>New recipe</h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Insert here a recipe that you love.</p>
    </div>
  </div>
</div>

<%= form_for @recipe do |f| %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="name">Name:</label>
          <%= f.text_field :name, class: "form-control", id: "name" %>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="form-group col-md-8">
          <label for="description">Description:</label>
          <%= f.text_area :description, class: "form-control", id: "description" %>
        </div>

    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipes_path, class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead"><%= @recipe.description %></p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p id="notice"><%= notice %><%= notice = '' %></p>
    </div>
  </div>



  <!-- Ingredients -->

  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h3>Ingredients</h3>
    </div>
  </div>
  <div class="row justify-content-md-center btn-row">
    <div class="col-lg-8">
      <%= link_to "<- Back", recipes_path, class: "btn btn-secondary float-left" %>
      <%= link_to "+ Ingredient", new_ingredient_path(recipe_id: @recipe.id), class: "btn btn-primary float-right" %>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Item</th>
            <th>Quantity</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.ingredients.each.with_index do |ing, index| %>
          <tr>
            <th scope="row"><%= index+1 %></th>
            <td><%= ing.name %></td>
            <td><%= ing.quantity %> <%= ing.measure %></td>
            <td><%= link_to 'Delete', ing, method: :delete, data: { confirm: 'Are you sure?' } %> |
                <%= link_to 'Edit', edit_ingredient_path(ing, recipe_id: @recipe.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Steps -->

  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h3>Steps</h3>
    </div>
  </div>
  <div class="row justify-content-md-center btn-row">
    <div class="col-lg-8">
      <%= link_to "<- Back", recipes_path, class: "btn btn-secondary float-left" %>
      <%= link_to "+ Step", new_step_path(recipe_id: @recipe.id), class: "btn btn-primary float-right" %>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Step</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe.steps.each.with_index do |step, index| %>
          <tr>
            <th scope="row"><%= index+1 %></th>
            <td><%= step.description %></td>
            <td><%= link_to 'Delete', step, method: :delete, data: { confirm: 'Are you sure?' } %> |
                <%= link_to 'Edit', edit_step_path(step, recipe_id: @recipe.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>

app/views/steps/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Edit step</p>
    </div>
  </div>
</div>

<%= form_for @step do |f| %>
<%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="description">Description:</label>
          <%= f.text_area :description, class: "form-control", id: "description" %>
        </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipe_path(id: params[:recipe_id]), class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/steps/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <h1><%= @recipe.name %></h1>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-xs-12">
      <p class="lead">Add step</p>
    </div>
  </div>
</div>

<%= form_for @step do |f| %>
<%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>
  <div class="container">
    <div class="row justify-content-md-center">
        <div class="form-group col-lg-8">
          <label for="description">Description:</label>
          <%= f.text_area :description, class: "form-control", id: "description" %>
        </div>
    </div>

    <div class="row justify-content-md-center">
      <div class="col-lg-8 text-right">
        <%= link_to 'Back', recipe_path(id: params[:recipe_id]), class: "btn btn-danger" %>
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>